### ISSUE TITLE
[Request] Body size

### ISSUE THREAD

**Issue by nullswan** [c3b5aw/webserv#9]
Handle body size being too large.

Client usually send Content-Length header withing their payload. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length)
We can use this header to prevent full reading of a payload.

In case the payload size is too large, we can return a 413 error. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

**Comment by nullswan** [comment]
Eventually need to decide how to manage the remaining connection.
From moxilla docs: (the server might close the connection or return a Retry-After header field.)

**Comment by gmarcha** [comment]
Je pense qu'on peut close la connexion ca serait plus facile a gerer, apres ca reste a voir, on peut faire en sorte de laisser la connexion open en utilisant juste un attribut en plus dans la request
Et sinon t'aurais quelle taille en tete pour un body "trop large" ?
